Task 1.1: Tạo Tensor

In [1]:
import torch 
import numpy as np 

# torch.set_default_device('cuda')
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data , dtype = torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.7884, 0.7643],
        [0.0043, 0.6637]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


Task 1.2 -> 1.4

In [ ]:
# Task 1.2: Các phép toán trên Tensor
# Cộng x_data với chính nó.
add_result = x_data + x_data
print(f"Kết quả cộng:\n{add_result}\n")
# Nhân x_data với 5.
mul_result = x_data * 5 
print(f"Kết quả nhân với 5:\n{mul_result}\n")
# Nhân ma trận x_data với x_data.T
matmul_result = x_data @ x_data.T
print(f"Kết quả nhân ma trận:\n{matmul_result}\n")

# Task 1.3: Indexing và Slicing (tensor x_data)
print(x_data) 
# Lấy ra hàng đầu tiên.
print(x_data[0])
# Lấy ra cột thứ hai. Cú pháp : x_data[hàng, cột]
print(x_data[:,1])
# Lấy ra giá trị ở hàng thứ hai, cột thứ hai.
print(x_data[1][1])
print("\n")

# Task 1.4: Thay đổi hình dạng Tensor
x = torch.rand(4, 4)
print(f"Tensor ban đầu (shape = {x.shape}):\n{x}\n")
x_view = x.view(16,1)
print(f"Tensor sau khi dùng view (shape = {x_view.shape}):\n{x_view}\n")
x_reshape = x.reshape(16,1)
print(f"Tensor sau khi dùng reshape (shape = {x_reshape.shape}):\n{x_reshape}\n")



Kết quả cộng:
tensor([[2, 4],
        [6, 8]])

Kết quả nhân với 5:
tensor([[ 5, 10],
        [15, 20]])

Kết quả nhân ma trận:
tensor([[ 5, 11],
        [11, 25]])

tensor([[1, 2],
        [3, 4]])
tensor([1, 2])
tensor([2, 4])
tensor(4)


Tensor ban đầu (shape = torch.Size([4, 4])):
tensor([[0.2990, 0.5416, 0.3956, 0.4471],
        [0.8649, 0.0684, 0.9303, 0.5316],
        [0.0167, 0.7225, 0.2498, 0.0896],
        [0.8294, 0.1239, 0.3857, 0.6010]])

Tensor sau khi dùng view (shape = torch.Size([16, 1])):
tensor([[0.2990],
        [0.5416],
        [0.3956],
        [0.4471],
        [0.8649],
        [0.0684],
        [0.9303],
        [0.5316],
        [0.0167],
        [0.7225],
        [0.2498],
        [0.0896],
        [0.8294],
        [0.1239],
        [0.3857],
        [0.6010]])

Tensor sau khi dùng reshape (shape = torch.Size([16, 1])):
tensor([[0.2990],
        [0.5416],
        [0.3956],
        [0.4471],
        [0.8649],
        [0.0684],
        [0.9303],
        [0.53

Task 2.1: Thực hành với autograd

- Khi  gọi z.backward(), PyTorch dùng biểu đồ tính toán (computation graph) để lan truyền đạo hàm ngược qua các phép toán đã thực hiện.

- Sau khi backward() chạy xong, để tiết kiệm bộ nhớ, PyTorch xóa biểu đồ này đi (vì mặc định cho rằng bạn không cần tính lại).

- Lần thứ hai gọi backward() → PyTorch không còn graph để đi ngược lại, nên nó báo lỗi.

In [15]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1 , requires_grad= True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3
print(f"z : {z}")

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

# Câu hỏi: Chuyện gì xảy ra nếu bạn gọi z.backward() một lần nữa? Tại sao?
# z.backward() 
# print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x000001C4081F79A0>
z : tensor([27.], grad_fn=<MulBackward0>)
Đạo hàm của z theo x: tensor([18.])


Phần 3: Xây dựng Mô hình đầu tiên với torch.nn

In [ ]:
# Task 3.1: Lớp nn.Linear
# Lớp nn.Linear thực hiện một phép biến đổi tuyến tính y = xA^T + b. ( nhân ma trận)
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)
# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều
# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Input : {input_tensor}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Input : tensor([[ 3.4342e-01,  1.2016e-01,  1.2447e-01,  7.2423e-01, -2.2925e+00],
        [ 1.9875e-03,  1.0882e+00,  8.3833e-01,  7.2331e-01,  2.3313e+00],
        [ 6.0936e-01,  1.3265e-01, -1.2524e+00,  9.9602e-01, -4.0548e-01]])
Output shape: torch.Size([3, 2])
Output:
 tensor([[ 0.4736, -1.0041],
        [-0.7091,  0.7435],
        [-0.3587, -0.1455]], grad_fn=<AddmmBackward0>)
